USE [master]
GO

/****** Object:  Database [Creditos]    Script Date: 15/10/2017 10:20:48 a.m. ******/
CREATE DATABASE [Creditos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Creditos', FILENAME = N'C:\udemy\WCF\Creditos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Creditos_log', FILENAME = N'C:\udemy\WCF\Creditos_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Creditos] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Creditos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Creditos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Creditos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Creditos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Creditos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Creditos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Creditos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Creditos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Creditos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Creditos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Creditos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Creditos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Creditos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Creditos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Creditos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Creditos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Creditos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Creditos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Creditos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Creditos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Creditos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Creditos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Creditos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Creditos] SET RECOVERY FULL 
GO

ALTER DATABASE [Creditos] SET  MULTI_USER 
GO

ALTER DATABASE [Creditos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Creditos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Creditos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Creditos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Creditos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Creditos] SET  READ_WRITE 
GO


