//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacagroup.Comercial.Creditos.ConsoleConsumer.ProxyCredito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCredito.ICreditoService")]
    public interface ICreditoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito[] ListarCredito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito[]> ListarCreditoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ObtenerCredito", ReplyAction="http://tempuri.org/ICreditoService/ObtenerCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito ObtenerCredito(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ObtenerCredito", ReplyAction="http://tempuri.org/ICreditoService/ObtenerCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ObtenerCreditoAsync(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        bool EliminarCredito(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoServiceChannel : Pacagroup.Comercial.Creditos.ConsoleConsumer.ProxyCredito.ICreditoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoServiceClient : System.ServiceModel.ClientBase<Pacagroup.Comercial.Creditos.ConsoleConsumer.ProxyCredito.ICreditoService>, Pacagroup.Comercial.Creditos.ConsoleConsumer.ProxyCredito.ICreditoService {
        
        public CreditoServiceClient() {
        }
        
        public CreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito[] ListarCredito() {
            return base.Channel.ListarCredito();
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito[]> ListarCreditoAsync() {
            return base.Channel.ListarCreditoAsync();
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito ObtenerCredito(string idCredito) {
            return base.Channel.ObtenerCredito(idCredito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ObtenerCreditoAsync(string idCredito) {
            return base.Channel.ObtenerCreditoAsync(idCredito);
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito credito) {
            return base.Channel.RegistrarCredito(credito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito credito) {
            return base.Channel.RegistrarCreditoAsync(credito);
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.Dominio.Credito credito) {
            return base.Channel.ActualizarCredito(credito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.Dominio.Credito credito) {
            return base.Channel.ActualizarCreditoAsync(credito);
        }
        
        public bool EliminarCredito(string idCredito) {
            return base.Channel.EliminarCredito(idCredito);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito) {
            return base.Channel.EliminarCreditoAsync(idCredito);
        }
    }
}
