//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credito", Namespace="http://schemas.datacontract.org/2004/07/Pacagroup.Comercial.Creditos.Dominio")]
    [System.SerializableAttribute()]
    public partial class Credito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ComisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DiaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoCreditoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Comision {
            get {
                return this.ComisionField;
            }
            set {
                if ((this.ComisionField.Equals(value) != true)) {
                    this.ComisionField = value;
                    this.RaisePropertyChanged("Comision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiaPago {
            get {
                return this.DiaPagoField;
            }
            set {
                if ((this.DiaPagoField.Equals(value) != true)) {
                    this.DiaPagoField = value;
                    this.RaisePropertyChanged("DiaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tasa {
            get {
                return this.TasaField;
            }
            set {
                if ((this.TasaField.Equals(value) != true)) {
                    this.TasaField = value;
                    this.RaisePropertyChanged("Tasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoCredito {
            get {
                return this.TipoCreditoField;
            }
            set {
                if ((this.TipoCreditoField.Equals(value) != true)) {
                    this.TipoCreditoField = value;
                    this.RaisePropertyChanged("TipoCredito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCredito.ICreditoService")]
    public interface ICreditoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito[] ListarCredito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ListarCredito", ReplyAction="http://tempuri.org/ICreditoService/ListarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito[]> ListarCreditoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ObtenerCredito", ReplyAction="http://tempuri.org/ICreditoService/ObtenerCreditoResponse")]
        Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito ObtenerCredito(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ObtenerCredito", ReplyAction="http://tempuri.org/ICreditoService/ObtenerCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> ObtenerCreditoAsync(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/RegistrarCredito", ReplyAction="http://tempuri.org/ICreditoService/RegistrarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ActualizarCredito", ReplyAction="http://tempuri.org/ICreditoService/ActualizarCreditoResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        bool EliminarCredito(string idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/EliminarCredito", ReplyAction="http://tempuri.org/ICreditoService/EliminarCreditoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoServiceChannel : Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoServiceClient : System.ServiceModel.ClientBase<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService>, Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.ICreditoService {
        
        public CreditoServiceClient() {
        }
        
        public CreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito[] ListarCredito() {
            return base.Channel.ListarCredito();
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito[]> ListarCreditoAsync() {
            return base.Channel.ListarCreditoAsync();
        }
        
        public Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito ObtenerCredito(string idCredito) {
            return base.Channel.ObtenerCredito(idCredito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> ObtenerCreditoAsync(string idCredito) {
            return base.Channel.ObtenerCreditoAsync(idCredito);
        }
        
        public Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito RegistrarCredito(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito) {
            return base.Channel.RegistrarCredito(credito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> RegistrarCreditoAsync(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito) {
            return base.Channel.RegistrarCreditoAsync(credito);
        }
        
        public Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito ActualizarCredito(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito) {
            return base.Channel.ActualizarCredito(credito);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito> ActualizarCreditoAsync(Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCredito.Credito credito) {
            return base.Channel.ActualizarCreditoAsync(credito);
        }
        
        public bool EliminarCredito(string idCredito) {
            return base.Channel.EliminarCredito(idCredito);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCreditoAsync(string idCredito) {
            return base.Channel.EliminarCreditoAsync(idCredito);
        }
    }
}
